In [1]:
# Generic inputs for most ML tasks
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
# This is new
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.ensemble import RandomForestRegressor

pd.options.display.float_format = '{:,.2f}'.format

# setup interactive notebook mode
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

from IPython.display import display, HTML
from sklearn.preprocessing import StandardScaler

In [2]:
# fetch data 

main_data = pd.read_csv('C:/Users/udayv/Downloads/Invistico_Airline.csv')
main_data.head()
print(main_data.columns)

,satisfaction,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Seat comfort,Departure/Arrival time convenient,Food and drink,...,Online support,Ease of Online booking,On-board service,Leg room service,Baggage handling,Checkin service,Cleanliness,Online boarding,Departure Delay in Minutes,Arrival Delay in Minutes
0,satisfied,Female,Loyal Customer,65,Personal Travel,Eco,265,0,0,0,...,2,3,3,0,3,5,3,2,0,0.00
1,satisfied,Male,Loyal Customer,47,Personal Travel,Business,2464,0,0,0,...,2,3,4,4,4,2,3,2,310,305.00
2,satisfied,Female,Loyal Customer,15,Personal Travel,Eco,2138,0,0,0,...,2,2,3,3,4,4,4,2,0,0.00
3,satisfied,Female,Loyal Customer,60,Personal Travel,Eco,623,0,0,0,...,3,1,1,0,1,4,1,3,0,0.00
4,satisfied,Female,Loyal Customer,70,Personal Travel,Eco,354,0,0,0,...,4,2,2,0,2,4,2,5,0,0.00

Index(['satisfaction', 'Gender', 'Customer Type', 'Age', 'Type of Travel',
       'Class', 'Flight Distance', 'Seat comfort',
       'Departure/Arrival time convenient', 'Food and drink', 'Gate location',
       'Inflight wifi service', 'Inflight entertainment', 'Online support',
       'Ease of Online booking', 'On-board service', 'Leg room service',
       'Baggage handling', 'Checkin service', 'Cleanliness', 'Online boarding',
       'Departure Delay in Minutes', 'Arrival Delay in Minutes'],
      dtype='object')

In [3]:
main_data.dropna(inplace=True)
main_data.isna().sum()

satisfaction                         0
Gender                               0
Customer Type                        0
Age                                  0
Type of Travel                       0
Class                                0
Flight Distance                      0
Seat comfort                         0
Departure/Arrival time convenient    0
Food and drink                       0
Gate location                        0
Inflight wifi service                0
Inflight entertainment               0
Online support                       0
Ease of Online booking               0
On-board service                     0
Leg room service                     0
Baggage handling                     0
Checkin service                      0
Cleanliness                          0
Online boarding                      0
Departure Delay in Minutes           0
Arrival Delay in Minutes             0
dtype: int64

In [4]:
# Drop 'satisfaction' column
main_data.drop(columns=['satisfaction'], inplace=True)
main_data.head()

,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Seat comfort,Departure/Arrival time convenient,Food and drink,Gate location,...,Online support,Ease of Online booking,On-board service,Leg room service,Baggage handling,Checkin service,Cleanliness,Online boarding,Departure Delay in Minutes,Arrival Delay in Minutes
0,Female,Loyal Customer,65,Personal Travel,Eco,265,0,0,0,2,...,2,3,3,0,3,5,3,2,0,0.00
1,Male,Loyal Customer,47,Personal Travel,Business,2464,0,0,0,3,...,2,3,4,4,4,2,3,2,310,305.00
2,Female,Loyal Customer,15,Personal Travel,Eco,2138,0,0,0,3,...,2,2,3,3,4,4,4,2,0,0.00
3,Female,Loyal Customer,60,Personal Travel,Eco,623,0,0,0,3,...,3,1,1,0,1,4,1,3,0,0.00
4,Female,Loyal Customer,70,Personal Travel,Eco,354,0,0,0,3,...,4,2,2,0,2,4,2,5,0,0.00

In [5]:
from sklearn.preprocessing import OneHotEncoder

def get_ohe(df, col):
    ohe = OneHotEncoder(drop='first', handle_unknown='error', sparse_output=False, dtype='int')
    ohe.fit(df[[col]])
    temp_df = pd.DataFrame(data=ohe.transform(df[[col]]), columns=ohe.get_feature_names_out())
    # If you have a newer version, replace with columns=ohe.get_feature_names_out()
    df.drop(columns=[col], axis=1, inplace=True)
    df = pd.concat([df.reset_index(drop=True), temp_df], axis=1)
    return df

In [6]:
main_data = get_ohe(main_data, 'Gender')
main_data = get_ohe(main_data, 'Customer Type')
main_data = get_ohe(main_data, 'Type of Travel')
main_data.head(20)
print(main_data.columns)

,Age,Class,Flight Distance,Seat comfort,Departure/Arrival time convenient,Food and drink,Gate location,Inflight wifi service,Inflight entertainment,Online support,...,Leg room service,Baggage handling,Checkin service,Cleanliness,Online boarding,Departure Delay in Minutes,Arrival Delay in Minutes,Gender_Male,Customer Type_disloyal Customer,Type of Travel_Personal Travel
0,65,Eco,265,0,0,0,2,2,4,2,...,0,3,5,3,2,0,0.00,0,0,1
1,47,Business,2464,0,0,0,3,0,2,2,...,4,4,2,3,2,310,305.00,1,0,1
2,15,Eco,2138,0,0,0,3,2,0,2,...,3,4,4,4,2,0,0.00,0,0,1
3,60,Eco,623,0,0,0,3,3,4,3,...,0,1,4,1,3,0,0.00,0,0,1
4,70,Eco,354,0,0,0,3,4,3,4,...,0,2,4,2,5,0,0.00,0,0,1
5,30,Eco,1894,0,0,0,3,2,0,2,...,4,5,5,4,2,0,0.00,1,0,1
6,66,Eco,227,0,0,0,3,2,5,5,...,0,5,5,5,3,17,15.00,0,0,1
7,10,Eco,1812,0,0,0,3,2,0,2,...,3,4,5,4,2,0,0.00,1,0,1
8,56,Business,73,0,0,0,3,5,3,5,...,0,1,5,4,4,0,0.00,0,0,1
9,22,Eco,1556,0,0,0,3,2,0,2,...,4,5,3,4,2,30,26.00,1,0,1
10,58,Eco,104,0,0,0,3,3,3,3,...,0,1,2,3,5,47,48.00,0,0,1
11,34,Eco,3633,0,0,0,4,2,0,2,...,2,5,2,5,2,0,0.00,0,0,1
12,62,Eco,1695,0,0,0,4,5,0,5,...,3,2,2,4,5,0,0.00,1,0,1
13,35,Eco,1766,0,1,0,1,4,0,4,...,5,2,3,2,4,0,0.00,1,0,1
14,47,Eco,84,0,1,0,1,5,2,1,...,0,5,2,5,2,40,48.00,0,0,1
15,60,Eco,1373,0,1,0,1,1,0,1,...,4,1,4,2,1,0,0.00,1,0,1
16,13,Eco,3693,0,1,0,2,4,0,4,...,4,1,3,1,4,5,0.00,0,0,1
17,52,Business,2610,0,1,0,2,1,2,2,...,0,1,2,1,3,0,0.00,0,0,1
18,55,Eco,2554,0,1,0,2,0,1,1,...,1,2,1,3,1,0,0.00,0,0,1
19,28,Eco,3095,0,1,0,2,3,0,3,...,5,2,3,2,3,0,0.00,0,0,1

Index(['Age', 'Class', 'Flight Distance', 'Seat comfort',
       'Departure/Arrival time convenient', 'Food and drink', 'Gate location',
       'Inflight wifi service', 'Inflight entertainment', 'Online support',
       'Ease of Online booking', 'On-board service', 'Leg room service',
       'Baggage handling', 'Checkin service', 'Cleanliness', 'Online boarding',
       'Departure Delay in Minutes', 'Arrival Delay in Minutes', 'Gender_Male',
       'Customer Type_disloyal Customer', 'Type of Travel_Personal Travel'],
      dtype='object')

In [10]:
independent_variables = main_data.drop(columns=['Class'])
print('Number of features(independent variables):',len(independent_variables.columns))
categorical_columns = independent_variables.select_dtypes(include=['object']).columns
categorical_values = independent_variables[categorical_columns]
print("Categorical values:")
print(categorical_columns)

Number of features(independent variables): 21
Categorical values:
Index([], dtype='object')

In [7]:
#2(c) Splitting data into train and test by randomly selecting 20% data in the test set
X_train, X_test, y_train, y_test = train_test_split(main_data.drop(columns = ['Class']), main_data['Class'], test_size=0.2, stratify = main_data['Class'], random_state=50)

# In the above split the stratify = y essentially makes sure the fractions of the classification is maintained
X_train
X_test
y_train
y_test

,Age,Flight Distance,Seat comfort,Departure/Arrival time convenient,Food and drink,Gate location,Inflight wifi service,Inflight entertainment,Online support,Ease of Online booking,...,Leg room service,Baggage handling,Checkin service,Cleanliness,Online boarding,Departure Delay in Minutes,Arrival Delay in Minutes,Gender_Male,Customer Type_disloyal Customer,Type of Travel_Personal Travel
100897,59,2559,1,1,1,1,5,4,5,4,...,4,4,3,4,4,0,0.00,1,0,0
76456,37,520,2,3,3,3,5,4,4,2,...,2,2,1,2,3,0,0.00,0,0,0
44676,26,1487,2,0,2,3,3,2,3,3,...,2,4,4,5,3,0,0.00,0,1,0
37815,50,550,4,5,4,4,1,5,5,5,...,4,5,3,5,1,0,0.00,0,0,1
122902,39,1980,5,1,5,5,5,5,5,5,...,3,5,5,1,5,0,0.00,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106779,46,2035,3,3,3,3,3,4,5,4,...,4,4,5,4,3,0,0.00,0,0,0
67611,54,269,1,3,4,3,2,3,4,1,...,1,1,3,1,4,49,64.00,0,0,0
119841,58,101,4,4,4,4,5,3,4,5,...,5,5,5,5,4,0,0.00,0,0,0
119381,55,309,1,1,1,1,2,4,4,5,...,5,5,3,5,5,0,0.00,0,0,0
111902,30,5585,3,3,3,3,4,5,4,4,...,4,4,3,4,4,0,0.00,0,0,0

,Age,Flight Distance,Seat comfort,Departure/Arrival time convenient,Food and drink,Gate location,Inflight wifi service,Inflight entertainment,Online support,Ease of Online booking,...,Leg room service,Baggage handling,Checkin service,Cleanliness,Online boarding,Departure Delay in Minutes,Arrival Delay in Minutes,Gender_Male,Customer Type_disloyal Customer,Type of Travel_Personal Travel
42248,32,1727,1,1,1,3,5,1,5,5,...,3,4,3,3,5,0,0.00,1,1,0
102458,57,1889,5,5,5,5,3,5,4,4,...,4,4,4,4,5,75,77.00,1,0,0
236,58,622,0,3,0,4,3,1,4,1,...,0,1,3,1,3,0,0.00,0,0,1
74922,41,2506,2,2,2,2,4,4,4,2,...,2,2,4,2,4,0,0.00,1,0,0
14632,40,3669,4,3,3,3,4,4,4,4,...,4,4,5,1,4,0,0.00,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102243,64,256,4,5,5,5,4,3,4,4,...,4,4,2,4,2,0,0.00,0,0,0
58476,26,2130,4,4,4,1,2,4,2,2,...,4,5,5,4,2,3,16.00,1,1,0
44093,26,2154,1,4,1,4,5,1,2,5,...,4,3,3,3,5,0,0.00,0,1,0
71815,72,1111,2,1,1,1,5,3,2,2,...,2,2,1,2,3,3,0.00,0,0,0
92998,40,1606,4,4,4,4,4,4,4,4,...,4,4,3,4,5,0,10.00,1,0,0

100897    Business
76456     Business
44676     Business
37815          Eco
122902         Eco
            ...
106779    Business
67611     Business
119841    Business
119381    Business
111902    Business
Name: Class, Length: 103589, dtype: object

42248     Business
102458    Business
236            Eco
74922     Business
14632          Eco
            ...
102243    Eco Plus
58476     Business
44093     Business
71815          Eco
92998     Business
Name: Class, Length: 25898, dtype: object

In [38]:
model = LogisticRegression(fit_intercept = True, solver='lbfgs', multi_class = 'ovr', penalty = None)
# If the lbfgs throws an error, try to increase max_iter (add max_iter = 1000), also try another algorithm, scaling is also suggested
# While using multiclass case do multi_class = 'over' or 'auto'; can also try other solvers
# While doing regularization, use penalty = 'l2' and also C = 10.0 (need to try other values too)

model.fit(X_train, y_train) 

# The following gives the mean accuracy on the given data and labels
model.score(X_train, y_train) 

# This is the coefficient Beta_1, ..., Beta_7
model.coef_

# This is the coefficient Beta_0
model.intercept_

LogisticRegression(multi_class='ovr', penalty=None)

0.7722924248713666

array([[ 1.91909513e-01,  3.98564637e-01, -7.49042660e-01,
         7.34851726e-02,  2.25677043e-01,  3.62123263e-02,
         5.86903190e-02,  5.72933352e-01,  3.13667760e-01,
        -3.81027711e-01,  3.51363951e-01,  1.21936900e-01,
         2.93750073e-01,  2.64333506e-01,  2.66719898e-01,
         1.56235249e-02,  1.06177017e-01, -1.67266544e-01,
         2.44929601e-02, -5.21252311e-01, -2.01935315e+00],
       [-1.23307346e-01, -3.00847061e-01,  4.94949056e-01,
        -2.97504921e-02, -1.70618861e-01, -3.00733362e-02,
        -5.08128033e-02, -3.71284598e-01, -2.14842603e-01,
         2.83462655e-01, -2.30311416e-01, -9.79085644e-02,
        -2.05560255e-01, -1.86828911e-01, -1.98968841e-01,
        -2.91336780e-02, -6.35521239e-02,  1.15617891e-01,
        -1.69519605e-02,  6.18804828e-01,  1.50379525e+00],
       [-1.01581380e-01, -2.06653435e-01,  2.69710429e-01,
         1.54163165e-03, -4.91504273e-02, -6.59060394e-02,
         3.50048215e-03, -2.60002757e-01, -1.40615983e-01,
         8.83727704e-02, -1.74832095e-01, -8.51298572e-02,
        -7.35314199e-02, -1.19555078e-01, -4.75738131e-02,
         1.01265725e-02, -1.01271488e-01,  1.09545792e-01,
        -8.25319498e-02, -2.95602924e-01,  2.59854596e-01]])

array([-0.2846731 , -0.31267784, -2.7345566 ])

In [12]:
model1000 = LogisticRegression(fit_intercept = True, solver='lbfgs', multi_class = 'ovr',max_iter=1000, penalty =None)
# If the lbfgs throws an error, try to increase max_iter (add max_iter = 1000), also try another algorithm, scaling is also suggested
# While using multiclass case do multi_class = 'over' or 'auto'; can also try other solvers
# While doing regularization, use penalty = 'l2' and also C = 10.0 (need to try other values too)

model1000.fit(X_train, y_train) 

# The following gives the mean accuracy on the given data and labels
model1000.score(X_train, y_train) 

# This is the coefficient Beta_1, ..., Beta_7
#model.coef_

# This is the coefficient Beta_0
#model.intercept_

C:\Users\udayv\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000, multi_class='ovr', penalty=None)

0.7686240817075172

In [21]:
sc = StandardScaler()
Xscaled_train = pd.DataFrame(sc.fit_transform(X_train), columns = X_train.columns, index = X_train.index)
Xscaled_test = pd.DataFrame(sc.transform(X_test), columns = X_test.columns, index = X_test.index)
Xscaled_train
Xscaled_test
y_train
y_test

,Age,Flight Distance,Seat comfort,Departure/Arrival time convenient,Food and drink,Gate location,Inflight wifi service,Inflight entertainment,Online support,Ease of Online booking,...,Leg room service,Baggage handling,Checkin service,Cleanliness,Online boarding,Departure Delay in Minutes,Arrival Delay in Minutes,Gender_Male,Customer Type_disloyal Customer,Type of Travel_Personal Travel
100897,1.29,0.56,-1.32,-1.30,-1.28,-1.52,1.33,0.46,1.13,0.41,...,0.40,0.26,-0.27,0.26,0.50,-0.38,-0.39,1.02,-0.47,-0.67
76456,-0.16,-1.42,-0.60,0.01,0.10,0.01,1.33,0.46,0.37,-1.13,...,-1.15,-1.47,-1.86,-1.48,-0.27,-0.38,-0.39,-0.98,-0.47,-0.67
44676,-0.89,-0.48,-0.60,-1.95,-0.59,0.01,-0.19,-1.03,-0.40,-0.36,...,-1.15,0.26,0.52,1.12,-0.27,-0.38,-0.39,-0.98,2.11,-0.67
37815,0.70,-1.39,0.84,1.32,0.80,0.78,-1.71,1.20,1.13,1.17,...,0.40,1.13,-0.27,1.12,-1.81,-0.38,-0.39,-0.98,-0.47,1.50
122902,-0.03,-0.00,1.55,-1.30,1.49,1.54,1.33,1.20,1.13,1.17,...,-0.38,1.13,1.32,-2.35,1.27,-0.38,-0.39,-0.98,-0.47,-0.67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106779,0.44,0.05,0.12,0.01,0.10,0.01,-0.19,0.46,1.13,0.41,...,0.40,0.26,1.32,0.26,-0.27,-0.38,-0.39,-0.98,-0.47,-0.67
67611,0.96,-1.67,-1.32,0.01,0.80,0.01,-0.95,-0.29,0.37,-1.89,...,-1.92,-2.34,-0.27,-2.35,0.50,0.90,1.26,-0.98,-0.47,-0.67
119841,1.23,-1.83,0.84,0.66,0.80,0.78,1.33,-0.29,0.37,1.17,...,1.17,1.13,1.32,1.12,0.50,-0.38,-0.39,-0.98,-0.47,-0.67
119381,1.03,-1.63,-1.32,-1.30,-1.28,-1.52,-0.95,0.46,0.37,1.17,...,1.17,1.13,-0.27,1.12,1.27,-0.38,-0.39,-0.98,-0.47,-0.67
111902,-0.62,3.51,0.12,0.01,0.10,0.01,0.57,1.20,0.37,0.41,...,0.40,0.26,-0.27,0.26,0.50,-0.38,-0.39,-0.98,-0.47,-0.67

,Age,Flight Distance,Seat comfort,Departure/Arrival time convenient,Food and drink,Gate location,Inflight wifi service,Inflight entertainment,Online support,Ease of Online booking,...,Leg room service,Baggage handling,Checkin service,Cleanliness,Online boarding,Departure Delay in Minutes,Arrival Delay in Minutes,Gender_Male,Customer Type_disloyal Customer,Type of Travel_Personal Travel
42248,-0.49,-0.25,-1.32,-1.30,-1.28,0.01,1.33,-1.77,1.13,1.17,...,-0.38,0.26,-0.27,-0.61,1.27,-0.38,-0.39,1.02,2.11,-0.67
102458,1.16,-0.09,1.55,1.32,1.49,1.54,-0.19,1.20,0.37,0.41,...,0.40,0.26,0.52,0.26,1.27,1.58,1.60,1.02,-0.47,-0.67
236,1.23,-1.32,-2.04,0.01,-1.98,0.78,-0.19,-1.77,0.37,-1.89,...,-2.70,-2.34,-0.27,-2.35,-0.27,-0.38,-0.39,-0.98,-0.47,1.50
74922,0.10,0.51,-0.60,-0.65,-0.59,-0.76,0.57,0.46,0.37,-1.13,...,-1.15,-1.47,0.52,-1.48,0.50,-0.38,-0.39,1.02,-0.47,-0.67
14632,0.04,1.64,0.84,0.01,0.10,0.01,0.57,0.46,0.37,0.41,...,0.40,0.26,1.32,-2.35,0.50,-0.38,-0.39,-0.98,-0.47,1.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102243,1.63,-1.68,0.84,1.32,1.49,1.54,0.57,-0.29,0.37,0.41,...,0.40,0.26,-1.06,0.26,-1.04,-0.38,-0.39,-0.98,-0.47,-0.67
58476,-0.89,0.14,0.84,0.66,0.80,-1.52,-0.95,0.46,-1.16,-1.13,...,0.40,1.13,1.32,0.26,-1.04,-0.31,0.02,1.02,2.11,-0.67
44093,-0.89,0.17,-1.32,0.66,-1.28,0.78,1.33,-1.77,-1.16,1.17,...,0.40,-0.60,-0.27,-0.61,1.27,-0.38,-0.39,-0.98,2.11,-0.67
71815,2.15,-0.85,-0.60,-1.30,-1.28,-1.52,1.33,-0.29,-1.16,-1.13,...,-1.15,-1.47,-1.86,-1.48,-0.27,-0.31,-0.39,-0.98,-0.47,-0.67
92998,0.04,-0.37,0.84,0.66,0.80,0.78,0.57,0.46,0.37,0.41,...,0.40,0.26,-0.27,0.26,1.27,-0.38,-0.13,1.02,-0.47,-0.67

100897    Business
76456     Business
44676     Business
37815          Eco
122902         Eco
            ...
106779    Business
67611     Business
119841    Business
119381    Business
111902    Business
Name: Class, Length: 103589, dtype: object

42248     Business
102458    Business
236            Eco
74922     Business
14632          Eco
            ...
102243    Eco Plus
58476     Business
44093     Business
71815          Eco
92998     Business
Name: Class, Length: 25898, dtype: object

In [22]:
modelscaled = LogisticRegression(fit_intercept = True, solver='lbfgs', multi_class = 'ovr', penalty =None)
# If the lbfgs throws an error, try to increase max_iter (add max_iter = 1000), also try another algorithm, scaling is also suggested
# While using multiclass case do multi_class = 'over' or 'auto'; can also try other solvers
# While doing regularization, use penalty = 'l2' and also C = 10.0 (need to try other values too)

modelscaled.fit(Xscaled_train, y_train) 

# The following gives the mean accuracy on the given data and labels
modelscaled.score(Xscaled_train, y_train) 

# This is the coefficient Beta_1, ..., Beta_7
#model.coef_

# This is the coefficient Beta_0
#model.intercept_

LogisticRegression(multi_class='ovr', penalty=None)

0.7722924248713666

In [23]:
modelnewton = LogisticRegression(fit_intercept = True, solver='newton-cg', multi_class = 'ovr', penalty = None)
# If the lbfgs throws an error, try to increase max_iter (add max_iter = 1000), also try another algorithm, scaling is also suggested
# While using multiclass case do multi_class = 'over' or 'auto'; can also try other solvers
# While doing regularization, use penalty = 'l2' and also C = 10.0 (need to try other values too)

modelnewton.fit(X_train, y_train) 

# The following gives the mean accuracy on the given data and labels
modelnewton.score(X_train, y_train) 

# This is the coefficient Beta_1, ..., Beta_7
#model.coef_

# This is the coefficient Beta_0
#model.intercept_

LogisticRegression(multi_class='ovr', penalty=None, solver='newton-cg')

0.7722924248713666

In [26]:
test_output1000 = pd.DataFrame(model1000.predict(X_test), index = X_test.index, columns = ['pred_Class'])
test_output1000.head()

       pred_Class
42248         Eco
102458   Business
236           Eco
74922    Business
14632         Eco

In [27]:
test_output1001 = test_output1000.merge(y_test, left_index = True, right_index = True)
test_output1001.head()
print('Percentage of correct predictions is ')
print(model1000.score(X_test, y_test))

       pred_Class     Class
42248         Eco  Business
102458   Business  Business
236           Eco       Eco
74922    Business  Business
14632         Eco       Eco

Percentage of correct predictions is
0.744150127422967

In [28]:
test_outputscaled = pd.DataFrame(modelscaled.predict(Xscaled_test), index = Xscaled_test.index, columns = ['pred_Class'])
test_outputscaled.head()

       pred_Class
42248         Eco
102458   Business
236           Eco
74922    Business
14632         Eco

In [29]:
test_outputscaled2 = test_outputscaled.merge(y_test, left_index = True, right_index = True)
test_outputscaled2.head()
print('Percentage of correct predictions is ')
print(modelscaled.score(Xscaled_test, y_test))

       pred_Class     Class
42248         Eco  Business
102458   Business  Business
236           Eco       Eco
74922    Business  Business
14632         Eco       Eco

Percentage of correct predictions is
0.7750791566916364

In [31]:
test_outputnewton = pd.DataFrame(modelnewton.predict(X_test), index = X_test.index, columns = ['pred_Class'])
test_outputnewton.head()

       pred_Class
42248         Eco
102458   Business
236           Eco
74922    Business
14632         Eco

In [32]:
test_outputnewton = test_outputnewton.merge(y_test, left_index = True, right_index = True)
test_outputnewton.head()
print('Percentage of correct predictions is ')
print(modelnewton.score(X_test, y_test))

       pred_Class     Class
42248         Eco  Business
102458   Business  Business
236           Eco       Eco
74922    Business  Business
14632         Eco       Eco

Percentage of correct predictions is
0.7750791566916364

In [33]:
test_outputscaled = pd.DataFrame(modelscaled.predict(Xscaled_test), index = Xscaled_test.index, columns = ['pred_Class'])
test_outputscaled.head()
test_outputscaled2 = test_outputscaled.merge(y_test, left_index = True, right_index = True)
test_outputscaled2.head()
print('Percentage of correct predictions is ')
print(modelscaled.score(Xscaled_test, y_test))

       pred_Class
42248         Eco
102458   Business
236           Eco
74922    Business
14632         Eco

       pred_Class     Class
42248         Eco  Business
102458   Business  Business
236           Eco       Eco
74922    Business  Business
14632         Eco       Eco

Percentage of correct predictions is
0.7750791566916364

In [34]:
# Count the number of times each class was predicted wrong
wrong_predictions_count = test_outputscaled2[test_outputscaled2['pred_Class'] != test_outputscaled2['Class']].groupby('Class').size()

# Find the class predicted wrong the most number of times
most_wrong_class = wrong_predictions_count.idxmax()

# Find the class predicted wrong the fewest times
fewest_wrong_class = wrong_predictions_count.idxmin()

print("Class predicted wrong the most number of times:", most_wrong_class)
print("Class predicted wrong the fewest times:", fewest_wrong_class)

Class predicted wrong the most number of times: Eco
Class predicted wrong the fewest times: Business

In [35]:
from sklearn.neighbors import KNeighborsClassifier
# Initialize the KNeighborsClassifier with 7 neighbors
knn_classifier = KNeighborsClassifier(n_neighbors=7)
# Train the KNeighborsClassifier
knn_classifier.fit(Xscaled_train, y_train)
# Calculate the score (fraction of accurate predictions) for the training data
train_score = knn_classifier.score(Xscaled_train, y_train)
print("Training Score:", train_score)

KNeighborsClassifier(n_neighbors=7)

Training Score: 0.8566063964320536

In [37]:
# Predict the 'Class' variable using the independent variables in the test set
predictions = knn_classifier.predict(Xscaled_test)

# Create a DataFrame with predicted and actual 'Class' values
prediction_df = pd.DataFrame({'Predicted_Class': predictions, 'Actual_Class': y_test})

# Calculate accuracy
accuracy = (predictions == y_test).mean()
print("Accuracy:", round(accuracy, 2))
prediction_df.head()

Accuracy: 0.83

       Predicted_Class Actual_Class
42248              Eco     Business
102458        Business     Business
236                Eco          Eco
74922         Business     Business
14632              Eco          Eco

In [39]:
penalty_data = pd.read_csv('C:/Users/udayv/Downloads/Invistico_Airline.csv')
penalty_data.dropna(inplace=True)
penalty_data.isna().sum()

satisfaction                         0
Gender                               0
Customer Type                        0
Age                                  0
Type of Travel                       0
Class                                0
Flight Distance                      0
Seat comfort                         0
Departure/Arrival time convenient    0
Food and drink                       0
Gate location                        0
Inflight wifi service                0
Inflight entertainment               0
Online support                       0
Ease of Online booking               0
On-board service                     0
Leg room service                     0
Baggage handling                     0
Checkin service                      0
Cleanliness                          0
Online boarding                      0
Departure Delay in Minutes           0
Arrival Delay in Minutes             0
dtype: int64

In [41]:
# Filter the dataset for 'Inflight entertainment' equal to 0
penalty_data = penalty_data[penalty_data['Inflight entertainment'] == 0]

# Define features and target variable
X = penalty_data.drop(columns=['satisfaction', 'Class', 'Inflight entertainment'])
y = penalty_data['Class']

# Perform one-hot encoding for categorical columns
X_encoded = pd.get_dummies(X, drop_first=True)

# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X_encoded, y, test_size=0.2, random_state=50, stratify=y)

# Scale the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Check the number of rows in the filtered dataset
num_rows = len(penalty_data)
print("Number of rows after filtering:", num_rows)

Number of rows after filtering: 2968

In [47]:

log_reg = LogisticRegression(fit_intercept = True,multi_class='ovr', solver='lbfgs', penalty=None)

# Fit the model on the training data
log_reg.fit(X_train_scaled, y_train)

log_reg.score(X_train_scaled, y_train)
log_reg.score(X_test_scaled,y_test)

LogisticRegression(multi_class='ovr', penalty=None)

0.780960404380792

0.7575757575757576

In [53]:
# Initialize the logistic regression model with L1 penalty
log_reg_l1 = LogisticRegression(penalty='l1', solver='liblinear', C=0.1, multi_class='ovr', random_state=0)

# Fit the model on the training data
log_reg_l1.fit(X_train_scaled, y_train)

# Calculate the test & train accuracy
train_accuracy_l1 = log_reg_l1.score(X_train_scaled,y_train)
test_accuracy_l1 = log_reg_l1.score(X_test_scaled, y_test)
print("Test Accuracy with L1 Penalty:", test_accuracy_l1)
print("Train Accuracy with L1 Penalty:",train_accuracy_l1)
# This is the coefficient Beta_1, ..., Beta_7
log_reg_l1.coef_

# This is the coefficient Beta_0
log_reg_l1.intercept_

LogisticRegression(C=0.1, multi_class='ovr', penalty='l1', random_state=0,
                   solver='liblinear')

Test Accuracy with L1 Penalty: 0.7643097643097643
Train Accuracy with L1 Penalty: 0.7771693344566133

array([[-3.48323967e-01,  4.35153327e-01,  0.00000000e+00,
        -2.88392005e-01,  0.00000000e+00,  8.80858289e-02,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.66913048e-01,  1.29702190e-01,  3.99486182e-01,
         1.41952550e-01,  3.55771405e-01,  0.00000000e+00,
         0.00000000e+00,  3.44771699e-02,  8.30846809e-03,
         8.10641852e-01, -5.50505379e-01],
       [ 9.04776764e-02, -2.50367806e-01,  4.58504115e-02,
         2.17884927e-01,  0.00000000e+00,  5.36017453e-04,
         0.00000000e+00,  2.67475004e-02,  1.24716865e-03,
        -1.46935767e-01, -6.77969206e-02, -2.13670557e-01,
        -1.26778644e-01, -2.07503611e-01,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  8.61664707e-01],
       [ 3.16985299e-02,  0.00000000e+00, -6.30100846e-02,
         0.00000000e+00,  0.00000000e+00, -1.67041688e-01,
         0.00000000e+00, -5.90909997e-02,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00, -3.63439345e-02,
         0.00000000e+00, -2.82023486e-03,  0.00000000e+00,
        -6.43770494e-03, -5.54317665e-02,  0.00000000e+00,
        -1.18591271e+00, -7.30749338e-01]])

array([-2.01962949,  0.84975817, -2.28844518])

In [54]:
# Get the coefficients and intercept of the model
coefficients = log_reg_l1.coef_
intercept = log_reg_l1.intercept_

# Get the feature names
feature_names = X.columns

# Create a DataFrame to display the coefficients for each feature
coefficients_df = pd.DataFrame(coefficients, columns=feature_names)

# Display the coefficients
print("Coefficients:")
print(coefficients_df)

# Identify features with (nearly) zero coefficients
zero_coefficients = coefficients_df.columns[coefficients_df.iloc[0] == 0]
print("\nFeatures with (nearly) zero coefficients:", zero_coefficients)

Coefficients:
   Gender  Customer Type   Age  Type of Travel  Flight Distance  Seat comfort  \
0   -0.35           0.44  0.00           -0.29             0.00          0.09
1    0.09          -0.25  0.05            0.22             0.00          0.00
2    0.03           0.00 -0.06            0.00             0.00         -0.17

   Departure/Arrival time convenient  Food and drink  Gate location  \
0                               0.00            0.00           0.00
1                               0.00            0.03           0.00
2                               0.00           -0.06           0.00

   Inflight wifi service  Online support  Ease of Online booking  \
0                   0.17            0.13                    0.40
1                  -0.15           -0.07                   -0.21
2                   0.00            0.00                   -0.04

   On-board service  Leg room service  Baggage handling  Checkin service  \
0              0.14              0.36              0.00             0.00
1             -0.13             -0.21              0.00             0.00
2              0.00             -0.00              0.00            -0.01

   Cleanliness  Online boarding  Departure Delay in Minutes  \
0         0.03             0.01                        0.81
1         0.00             0.00                        0.00
2        -0.06             0.00                       -1.19

   Arrival Delay in Minutes
0                     -0.55
1                      0.86
2                     -0.73

Features with (nearly) zero coefficients: Index(['Age', 'Flight Distance', 'Departure/Arrival time convenient',
       'Food and drink', 'Gate location', 'Baggage handling',
       'Checkin service'],
      dtype='object')

In [55]:
# Initialize the logistic regression model with L2 penalty
log_reg_l2 = LogisticRegression(penalty='l2', solver='lbfgs', C=0.1, multi_class='ovr', random_state=0)

# Fit the model on the training data
log_reg_l2.fit(X_train_scaled, y_train)

# Calculate the test accuracy
test_accuracy_l2 = log_reg_l2.score(X_test_scaled, y_test)
print("Test Accuracy with L2 Penalty:", test_accuracy_l2)

# Calculate the train accuracy
train_accuracy_l2 = log_reg_l2.score(X_train_scaled, y_train)
print("Train Accuracy with L2 Penalty:", train_accuracy_l2)

LogisticRegression(C=0.1, multi_class='ovr', random_state=0)

Test Accuracy with L2 Penalty: 0.765993265993266
Train Accuracy with L2 Penalty: 0.7805391743892165